name: portfolio
services:
  frontend:
    build: ./
    container_name: frontend
    ports:
      - "9000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:9000/
      - NODE_ENV=development